void buffer_overflow_001_P();
void buffer_overflow_001_N();
void buffer_overflow_002_P();
void buffer_overflow_002_N();
void buffer_overflow_003();
void buffer_overflow_004_P(char * src);
void buffer_overflow_004_N(char * src);
void buffer_overflow_005_P();
void buffer_overflow_005_N();
void null_pointer_dereference_004_P(int sensorNum); 
int divions_by_zero_001_P();
int divions_by_zero_002_P();
int divions_by_zero_002_N();
void freeing_non_heap_memory_002_P();
void memory_leak_001(char* foo);